# Generated by Django 4.0.2 on 2022-02-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_today_day_alter_todo_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='checking',
        ),
        migrations.AddField(
            model_name='todo',
            name='made',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.TextField(),
        ),
    ]
